# Generated by Django 4.2 on 2024-11-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('years_experience', models.PositiveSmallIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breed', models.CharField(max_length=100)),
            ],
        ),
    ]
